ER-Diagram
```mermaid
erDiagram
    User {
        int User_ID PK
        varchar Firstname
        varchar Name
        varchar Username
        varchar Password
        varchar E-Mail
        varchar Telephone
        text Additional_Description
        boolean License_Verified
        blob Profile_Picture
        datetime Creation_Date
        int Address_ID FK
        int Role_ID FK
        int Status_ID FK
    }

    Vehicle_Mapping {
        int Vehicle_Mapping_ID PK
        decimal Fuel_Milage
        text Additional_Info
        varchar License_Plate
        int Vehicle_ID FK
        int User_ID FK
        int Status_ID FK
    }

    Status {
        int Status_ID PK
        varchar Status_Description
    }

    Role {
        int Role_ID PK
        varchar Name
        text Description
    }

    Address {
        int Address_ID PK
        varchar City
        varchar Postal_Code
        varchar Street
        varchar Country
        varchar Country_Code
        varchar Region
        varchar State
        double Longitude
        double Latitude
        varchar Address_Line1
        varchar Address_Line2
        int Status_ID FK
    }

    Vehicle {
        int Vehicle_Mapping_ID PK
        varchar Model
        int Seats
        int Year_of_manufacture
        varchar Manufacturer_Name
        int Status_ID FK
    }

    Event {
        int Event_ID PK
        varchar Type
        int Free_Seats
        text Description
        datetime Start_Timestamp
        int Schedule_ID FK
        int Status_ID FK
    }

    Event_Member {
        int Member_ID PK
        varchar Type
        int User_ID FK
        int Event_ID FK
        int Status_ID FK
    }

    Chat_Message {
        int Chat_Message_ID PK
        text Message
        datetime Timestamp
        int User_ID FK
        int Event_ID FK
    }

    Invite {
        int Invite_ID PK
        varchar Confirmation_Status
        boolean Is_Request
        int Event_ID FK
        int User_ID FK
    }

    Notification {
        int Notification_ID PK
        boolean Read
        text Message
        varchar Entity_Type
        int Entity_ID FK
        int User_ID FK
    }

    Stop {
        int Stop_ID PK
        int Stop_sequence_number
        int Address_ID FK
        int Event_ID FK
    }

    Schedule {
        int Schedule_ID PK
        varchar Cron_Schedule
        int User_ID FK
    }

    Audit {
        int Audit_ID PK
        text Message
        varchar Entity_Type
        datetime Timestamp
        int Entity_ID FK
        int User_ID FK
    }

    Rating {
        int Rating_ID PK
        text Rating_Text
        int Rating_Value
        int Rated_user_ID FK
        int User_who_rated_ID FK
        int Status_ID FK
    }

    User }|--o{ Vehicle_Mapping : owns
    User ||--o{ Event_Member : "member of"
    User ||--o{ Chat_Message : "sent by"
    User ||--o{ Invite : invited
    User ||--o{ Notification : notified
    User ||--o{ Schedule : "created by"
    User ||--o{ Audit : "did"
    User ||--o{ Rating : "received"
    Rating }o--|| User : "rated"
    Vehicle_Mapping }o--|| Vehicle : "is"
    Vehicle_Mapping }o--|| Status : "is"
    Status ||--o{ Address : "is"
    Status ||--o{ Vehicle : "is"
    Status ||--o{ Event : "is"
    Status ||--o{ Event_Member : "is"
    Status ||--o{ Rating : "is"
    Role ||--o{ User : "has"
    Address ||--o{ Stop : "is a stop at"
    Address ||--o{ User : "lives at"
    Event ||--o{ Event_Member : "takes part in"
    Event ||--o{ Chat_Message : "sent in"
    Event ||--o{ Invite : "created for"
    Event ||--|{ Stop : "has stops"
    Schedule |o--o{ Event : "has"
```